### ISSUE TITLE
Issue loading Pokemon models

### ISSUE THREAD

**Issue by PriChama** [Turk645/PokemonMasters#1]
I was trying to import the pokemon models and got this error;
![poke](https://user-images.githubusercontent.com/41806074/63132653-2ab88b80-bf7f-11e9-8a08-7f479a98a0cf.png)

I was hoping you could look at it!

Some samples just incase;
[Sam.zip](https://github.com/Turk645/PokemonMasters/files/3507459/Sam.zip)

**Comment by Turk645** [comment]
the pokemon meshes had some extra info i didnt take into consideration. Fix in latest update.
